### ISSUE TITLE
Certbot 2.X no longer depends on zope

### ISSUE THREAD

**Issue by michael-caraccio-colorix** [Infomaniak/certbot-dns-infomaniak#23]
Hello,

Since certbot version 2.0.0 - 2022-11-21, certbot doesnt use zope anymore, which means that  zope interfaces are not found.

Certbot release not about Zope being deprecated : 
https://github.com/certbot/certbot/blob/f0251a7959af4f92bdb0903d921d3ed0da02179f/certbot/CHANGELOG.md

More info here : https://github.com/certbot/certbot/wiki/Certbot-v2.x-Plugin-Compatibility

Error :
```
2022-12-05 11:29:19,398 P10041 [INFO] 	Exiting abnormally:
2022-12-05 11:29:19,398 P10041 [INFO] 	Traceback (most recent call last):
2022-12-05 11:29:19,398 P10041 [INFO] 	  File "/usr/local/bin/certbot", line 8, in <module>
2022-12-05 11:29:19,399 P10041 [INFO] 	    sys.exit(main())
2022-12-05 11:29:19,399 P10041 [INFO] 	  File "/usr/local/lib/python3.7/site-packages/certbot/main.py", line 19, in main
2022-12-05 11:29:19,399 P10041 [INFO] 	    return internal_main.main(cli_args)
2022-12-05 11:29:19,399 P10041 [INFO] 	  File "/usr/local/lib/python3.7/site-packages/certbot/_internal/main.py", line 1707, in main
2022-12-05 11:29:19,399 P10041 [INFO] 	    plugins = plugins_disco.PluginsRegistry.find_all()
2022-12-05 11:29:19,399 P10041 [INFO] 	  File "/usr/local/lib/python3.7/site-packages/certbot/_internal/plugins/disco.py", line 208, in find_all
2022-12-05 11:29:19,399 P10041 [INFO] 	    cls._load_entry_point(entry_point, plugins)
2022-12-05 11:29:19,399 P10041 [INFO] 	  File "/usr/local/lib/python3.7/site-packages/certbot/_internal/plugins/disco.py", line 215, in _load_entry_point
2022-12-05 11:29:19,399 P10041 [INFO] 	    plugin_ep = PluginEntryPoint(entry_point)
2022-12-05 11:29:19,399 P10041 [INFO] 	  File "/usr/local/lib/python3.7/site-packages/certbot/_internal/plugins/disco.py", line 56, in __init__
2022-12-05 11:29:19,399 P10041 [INFO] 	    self.plugin_cls: Type[interfaces.Plugin] = entry_point.load()
2022-12-05 11:29:19,399 P10041 [INFO] 	  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2471, in load
2022-12-05 11:29:19,399 P10041 [INFO] 	    return self.resolve()
2022-12-05 11:29:19,399 P10041 [INFO] 	  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2477, in resolve
2022-12-05 11:29:19,399 P10041 [INFO] 	    module = __import__(self.module_name, fromlist=['__name__'], level=0)
2022-12-05 11:29:19,399 P10041 [INFO] 	  File "/usr/local/lib/python3.7/site-packages/certbot_dns_infomaniak/dns_infomaniak.py", line 20, in <module>
2022-12-05 11:29:19,399 P10041 [INFO] 	    @zope.interface.implementer(interfaces.IAuthenticator)
2022-12-05 11:29:19,399 P10041 [INFO] 	AttributeError: module 'certbot.interfaces' has no attribute 'IAuthenticator'
2022-12-05 11:29:19,399 P10041 [INFO] 	Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/certbot-log-oh0lz2oc/log or re-run Certbot with -v for more details.
```

**Comment by reneluria** [comment]
Hello, thank you for your comment, will fix asap
