### ISSUE TITLE
Encountered exception during recovery: IndexError: list index out of range

### ISSUE THREAD

**Issue by prohand** [Infomaniak/certbot-dns-infomaniak#40]
Hello,

I have an error to renew a certificate.

I have this error : 

```
2024-12-04 10:38:57,103:DEBUG:acme.client:Storing nonce: zIaIDaiTVyjLI5-Qfo_RRJDqZyObj_nAaV6YfowsNdA-lJ0gzbU
2024-12-04 10:38:57,104:INFO:certbot._internal.auth_handler:Performing the following challenges:
2024-12-04 10:38:57,105:INFO:certbot._internal.auth_handler:dns-01 challenge for paste.srv-home.fr
2024-12-04 10:38:57,107:DEBUG:certbot_dns_infomaniak.dns_infomaniak:add_txt_record paste.srv-home.fr _acme-challenge.paste.srv-home.fr ElsYKq904sZldx-FNPVjS0bnUDN4gbV2KCWeDMNX8I0
2024-12-04 10:38:57,107:DEBUG:certbot_dns_infomaniak.dns_infomaniak:GET https://api.infomaniak.com/1/product?service_name=domain&customer_name=paste.srv-home.fr
2024-12-04 10:38:57,108:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.infomaniak.com:443
2024-12-04 10:38:57,285:DEBUG:urllib3.connectionpool:https://api.infomaniak.com:443 "GET /1/product?service_name=domain&customer_name=paste.srv-home.fr HTTP/1.1" 200 30
2024-12-04 10:38:57,286:DEBUG:certbot_dns_infomaniak.dns_infomaniak:GET https://api.infomaniak.com/1/product?service_name=domain&customer_name=srv-home.fr
2024-12-04 10:38:57,380:DEBUG:urllib3.connectionpool:https://api.infomaniak.com:443 "GET /1/product?service_name=domain&customer_name=srv-home.fr HTTP/1.1" 200 467
2024-12-04 10:38:57,381:DEBUG:certbot_dns_infomaniak.dns_infomaniak:1208015 / srv-home.fr
2024-12-04 10:38:57,382:DEBUG:certbot_dns_infomaniak.dns_infomaniak:add_txt_record srv-home.fr _acme-challenge.paste ElsYKq904sZldx-FNPVjS0bnUDN4gbV2KCWeDMNX8I0
2024-12-04 10:38:57,382:DEBUG:certbot_dns_infomaniak.dns_infomaniak:POST https://api.infomaniak.com/1/domain/1208015/dns/record
2024-12-04 10:38:57,521:DEBUG:urllib3.connectionpool:https://api.infomaniak.com:443 "POST /1/domain/1208015/dns/record HTTP/1.1" 422 214
2024-12-04 10:38:57,525:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/root/.venv/lib/python3.12/site-packages/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
    resps = self.auth.perform(achalls)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venv/lib/python3.12/site-packages/certbot/plugins/dns_common.py", line 76, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/root/.venv/lib/python3.12/site-packages/certbot_dns_infomaniak/dns_infomaniak.py", line 64, in _perform
    self._api_client().add_txt_record(decoded_domain, validation_name, validation)
  File "/root/.venv/lib/python3.12/site-packages/certbot_dns_infomaniak/dns_infomaniak.py", line 221, in add_txt_record
    self._post_request("/1/domain/{domain_id}/dns/record".format(domain_id=domain_id), data)
  File "/root/.venv/lib/python3.12/site-packages/certbot_dns_infomaniak/dns_infomaniak.py", line 130, in _post_request
    raise errors.PluginError(
certbot.errors.PluginError: error in API request: validation_failed / Validation failed

2024-12-04 10:38:57,525:DEBUG:certbot._internal.error_handler:Calling registered functions
2024-12-04 10:38:57,525:INFO:certbot._internal.auth_handler:Cleaning up challenges
2024-12-04 10:38:57,526:DEBUG:certbot_dns_infomaniak.dns_infomaniak:del_txt_record paste.srv-home.fr _acme-challenge.paste.srv-home.fr ElsYKq904sZldx-FNPVjS0bnUDN4gbV2KCWeDMNX8I0
2024-12-04 10:38:57,526:DEBUG:certbot_dns_infomaniak.dns_infomaniak:GET https://api.infomaniak.com/1/product?service_name=domain&customer_name=paste.srv-home.fr
2024-12-04 10:38:57,528:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.infomaniak.com:443
2024-12-04 10:38:57,676:DEBUG:urllib3.connectionpool:https://api.infomaniak.com:443 "GET /1/product?service_name=domain&customer_name=paste.srv-home.fr HTTP/1.1" 200 30
2024-12-04 10:38:57,676:DEBUG:certbot_dns_infomaniak.dns_infomaniak:GET https://api.infomaniak.com/1/product?service_name=domain&customer_name=srv-home.fr
2024-12-04 10:38:57,773:DEBUG:urllib3.connectionpool:https://api.infomaniak.com:443 "GET /1/product?service_name=domain&customer_name=srv-home.fr HTTP/1.1" 200 467
2024-12-04 10:38:57,773:DEBUG:certbot_dns_infomaniak.dns_infomaniak:del_txt_record srv-home.fr _acme-challenge.paste ElsYKq904sZldx-FNPVjS0bnUDN4gbV2KCWeDMNX8I0
2024-12-04 10:38:57,774:DEBUG:certbot_dns_infomaniak.dns_infomaniak:GET https://api.infomaniak.com/1/domain/1208015/dns/record
2024-12-04 10:38:57,874:DEBUG:urllib3.connectionpool:https://api.infomaniak.com:443 "GET /1/domain/1208015/dns/record HTTP/1.1" 200 None
2024-12-04 10:38:57,897:ERROR:certbot._internal.error_handler:Encountered exception during recovery: IndexError: list index out of range
2024-12-04 10:38:57,897:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.venv/bin/certbot", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/.venv/lib/python3.12/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venv/lib/python3.12/site-packages/certbot/_internal/main.py", line 1894, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venv/lib/python3.12/site-packages/certbot/_internal/main.py", line 1600, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venv/lib/python3.12/site-packages/certbot/_internal/main.py", line 131, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/root/.venv/lib/python3.12/site-packages/certbot/_internal/renewal.py", line 399, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venv/lib/python3.12/site-packages/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venv/lib/python3.12/site-packages/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venv/lib/python3.12/site-packages/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
    resps = self.auth.perform(achalls)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venv/lib/python3.12/site-packages/certbot/plugins/dns_common.py", line 76, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/root/.venv/lib/python3.12/site-packages/certbot_dns_infomaniak/dns_infomaniak.py", line 64, in _perform
    self._api_client().add_txt_record(decoded_domain, validation_name, validation)
  File "/root/.venv/lib/python3.12/site-packages/certbot_dns_infomaniak/dns_infomaniak.py", line 221, in add_txt_record
    self._post_request("/1/domain/{domain_id}/dns/record".format(domain_id=domain_id), data)
  File "/root/.venv/lib/python3.12/site-packages/certbot_dns_infomaniak/dns_infomaniak.py", line 130, in _post_request
    raise errors.PluginError(
certbot.errors.PluginError: error in API request: validation_failed / Validation failed
2024-12-04 10:38:57,903:ERROR:certbot._internal.log:error in API request: validation_failed / Validation failed
```

Do you have a solution ?

Thank you

**Comment by prouveyrol** [comment]
Hello, I can confirm this is not an isolated case, on Ubuntu 24.04, running python3-certbot-dns-infomaniak/noble,noble,now 0.2.2-1 all I get the exact same error.

Best regards.

**Comment by Zignet64** [comment]
Hi,

Same issue here :/ 

`2024-12-05 10:37:13,683:DEBUG:urllib3.connectionpool:https://api.infomaniak.com:443 "GET /1/domain/845676/dns/record HTTP/1.1" 200 1203
2024-12-05 10:37:13,684:ERROR:certbot._internal.error_handler:Encountered exception during recovery: IndexError: list index out of range
2024-12-05 10:37:13,684:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot==2.1.0', 'console_scripts', 'certbot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/certbot/_internal/main.py", line 1736, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/certbot/_internal/main.py", line 1590, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/certbot/_internal/main.py", line 138, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/certbot/_internal/client.py", line 516, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/certbot/_internal/auth_handler.py", line 86, in handle_authorizations
    resps = self.auth.perform(achalls)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 76, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/local/lib/python3.11/dist-packages/certbot_dns_infomaniak/dns_infomaniak.py", line 64, in _perform
    self._api_client().add_txt_record(decoded_domain, validation_name, validation)
  File "/usr/local/lib/python3.11/dist-packages/certbot_dns_infomaniak/dns_infomaniak.py", line 221, in add_txt_record
    self._post_request("/1/domain/{domain_id}/dns/record".format(domain_id=domain_id), data)
  File "/usr/local/lib/python3.11/dist-packages/certbot_dns_infomaniak/dns_infomaniak.py", line 130, in _post_request
    raise errors.PluginError(
certbot.errors.PluginError: error in API request: validation_failed / Validation failed
2024-12-05 10:37:13,687:ERROR:certbot._internal.log:error in API request: validation_failed / Validation failed`

**Comment by NevilleDubuis** [comment]
after some tests with POSTMAN it seemed to me that the error is that the header `Content-Type: application/json` is missing: 

here is the response i get if remove the `Content-Type` Header : 
```
{
    "result": "error",
    "error": {
        "code": "validation_failed",
        "description": "Validation failed",
        "errors": [
            {
                "code": "validation_rule_required",
                "description": "The type field is required.",
                "context": {
                    "attribute": "type"
                }
            },
            {
                "code": "validation_rule_required_unless",
                "description": "The target field is required unless type is in DMARC.",
                "context": {
                    "attribute": "target",
                    "other": "type",
                    "other_value": null,
                    "values": [
                        "DMARC"
                    ]
                }
            },
            {
                "code": "validation_rule_required",
                "description": "The ttl field is required.",
                "context": {
                    "attribute": "ttl"
                }
            }
        ]
    }
}
```

Sadly being not familiar with python, i'm not sure how to make the fix

**Comment by reneluria** [comment]
Excellent, thank you @NevilleDubuis for the fix and @Zignet64 for the report

**Comment by prohand** [comment]
Thanks
